# Generated by Django 5.0.1 on 2025-11-12 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='telefone_contato',
            field=models.CharField(blank=True, help_text='Telefone para contato na entrega (opcional)', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve conter 10 ou 11 dígitos', regex='^\\d{10,11}$')], verbose_name='Telefone de Contato'),
        ),
    ]
