# Generated by Django 5.0.1 on 2025-11-12 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_endereco_telefone_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Telefone deve conter 10 ou 11 dígitos', regex='^\\d{10,11}$')], verbose_name='Telefone'),
        ),
    ]
