# Generated by Django 5.0.1 on 2025-11-12 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='CEP deve conter 8 dígitos', regex='^\\d{8}$')], verbose_name='CEP'),
        ),
    ]
