# Generated by Django 5.0.1 on 2025-11-10 02:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição', verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('descricao_curta', models.CharField(blank=True, help_text='Descrição breve para listagens', max_length=255, verbose_name='Descrição Curta')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço')),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Promocional')),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, help_text='Preço de custo (não mostrado ao cliente)', max_digits=10, null=True, verbose_name='Preço de Custo')),
                ('estoque', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque')),
                ('estoque_minimo', models.IntegerField(default=5, help_text='Alerta quando estoque atingir este valor', verbose_name='Estoque Mínimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('em_destaque', models.BooleanField(default=False, verbose_name='Em Destaque')),
                ('disponivel', models.BooleanField(default=True, help_text='Desmarque para ocultar temporariamente sem desativar', verbose_name='Disponível')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/%Y/%m/', verbose_name='Imagem')),
                ('meta_description', models.CharField(blank=True, help_text='Descrição para mecanismos de busca', max_length=160, verbose_name='Meta Descrição')),
                ('meta_keywords', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=255, verbose_name='Palavras-chave')),
                ('visualizacoes', models.IntegerField(default=0, editable=False, verbose_name='Visualizações')),
                ('vendas', models.IntegerField(default=0, editable=False, verbose_name='Vendas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/%Y/%m/galeria/', verbose_name='Imagem')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens dos Produtos',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['slug'], name='produtos_pr_slug_e58355_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ativo', 'disponivel'], name='produtos_pr_ativo_2f60c5_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['-criado_em'], name='produtos_pr_criado__799012_idx'),
        ),
    ]
