# Generated by Django 5.2.8 on 2025-11-08 02:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria_alter_produto_options_produto_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/%Y/%m/galeria/')),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens dos Produtos',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição'),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao_curta',
            field=models.CharField(blank=True, help_text='Descrição breve para listagens', max_length=255),
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Desmarque para ocultar temporariamente sem desativar'),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=5, help_text='Alerta quando estoque atingir este valor'),
        ),
        migrations.AddField(
            model_name='produto',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descrição para mecanismos de busca', max_length=160),
        ),
        migrations.AddField(
            model_name='produto',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=255),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço de custo (não mostrado ao cliente)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='vendas',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='visualizacoes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['slug'], name='produtos_pr_slug_e58355_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ativo', 'disponivel'], name='produtos_pr_ativo_2f60c5_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['-criado_em'], name='produtos_pr_criado__799012_idx'),
        ),
        migrations.AddField(
            model_name='imagemproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produtos.produto'),
        ),
    ]
