# Generated by Django 5.0.1 on 2025-11-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='Número do Pedido'),
        ),
    ]
